### ISSUE TITLE
Model is not running -> issue in the SAVEhh variable 

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE#202] opened 2023-10-12 10:39 UTC
Hi all, 

I am a new user of STEMMUS_SCOPE. I am trying to follow the guidelines to run the model. But I have quite a few issues. The first one is that I can't find the filesread.m in the src folder of this repo. As I understand following the **how_to_run_on_Crib guidelines** (https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/docs/STEMMUS_SCOPE_on_CRIB.md), I need to open the filesread.m file and set the variable CFG to the path of the config file  

Could you please give me a guide? @yijianzeng 

Thanks a lot in advance
Mostafa

**Comment by SarahAlidoost** [comment] 2023-10-17 08:45
@MostafaGomaa93 thanks for submitting the issue. The instructions is outdated since we are refactoring the stemmus_scope code. You can set the path to `CFG` variable in `STEMMUS_SCOPE.m `main script, see [this line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/9dc322fef9e6806a4427335e5e1794c2b42c2e38/src/STEMMUS_SCOPE.m#L29).

**Comment by MostafaGomaa93** [comment] 2023-10-20 09:35
@SarahAlidoost, thanks for your answer.

I am already facing another path issue. I can't find the Mdata.txt file in the src code which as I understand will be used to create the forcing_global.mat file. Can you please give me a guide?

**Comment by SarahAlidoost** [comment] 2023-10-20 10:24
> I am already facing another path issue. I can't find the Mdata.txt file in the src code which as I understand will be used to create the forcing_global.mat file. Can you please give me a guide?

`Mdata.txt` is a part of the input data to the model rather than the source code. It should be already available in the input folder. Here are my suggestions:
1- make sure you are using the[ latest version of stemmus_scope](https://github.com/EcoExtreML/STEMMUS_SCOPE/releases/tag/1.4.0)
2- use `pystemmusscope` to prepare input data, see [documentation](https://pystemmusscope.readthedocs.io/en/v0.2.0/notebooks/run_model_in_notebook/)

@Yunfei-Wang1993, @yijianzeng, @Crystal-szj and @DanyangYu  since you are familiar with the packages and how to use them on CRIB, could you please help @MostafaGomaa93 to run the model?

**Comment by Crystal-szj** [comment] 2023-10-21 10:40
Hi @MostafaGomaa93, you can use CRIB to run the latest version of STEMMUS-SCOPE. Before running, the input data can be created by `PyStemmusScope`, a pre-processing package for preparing the requested input data of STEMMUS-SCOPE. 
1. Download the `PyStemmusScope` and the latest version of `STEMMUS_SCOPE` to your workspace.
```
git clone git@github.com:EcoExtreML/STEMMUS_SCOPE_Processing.git
git clone git@github.com:EcoExtreML/STEMMUS_SCOPE.git
```
2. Install PyStemmusScope, see [here](https://pystemmusscope.readthedocs.io/en/v0.2.0/installation_instructions/). This step can create all the requested input data of STEMMUS_SCOPE and run the model directly. In [Section 2 Using Matlab -- cell 7](https://pystemmusscope.readthedocs.io/en/v0.2.0/notebooks/run_model_in_notebook/), `result = model.run()` is running the STEMMUS_SCOPE via Jupyter notebook, and if you run it successfully, the result should be saved in `OutputPath`.

You can also try the above step on your own computer if your computer has a Linux system. Noted the WSL in the Window system can not write the output of PyStemmusScope since the WSL doesn't have the write permission.

**Comment by SarahAlidoost** [comment] 2023-11-01 08:38
@MostafaGomaa93 There are several issues with how you are trying to run the model. Here are the list of possible solutions:
1- You are using a command `python3 run_model_matlab.py` in a `base` conda environment. This is not illustrated anywhere in the documentation! I suggest using only the options mentioned in the documentation, see section **Which options are available?**  [here](https://pystemmusscope.readthedocs.io/en/latest/notebooks/run_model_in_notebook/). Please note the Matlab, Matlab runtime and python versions that are mentioned in the documentation.
2- Also, the running model on the `ITC Linux668` has not been tested. Please see the [installation options](https://pystemmusscope.readthedocs.io/en/latest/installation_instructions/) and the machines in the documentation. 
3- You are using the notebook in the version v0.2.0. The latest version of pystemmuscope is 0.3.0, see the notebook [here](https://pystemmusscope.readthedocs.io/en/latest/notebooks/run_model_in_notebook/). 
4- Please follow the steps in the documentation as: 1. [Getting started](https://pystemmusscope.readthedocs.io/en/latest/), 2. [Installation](https://pystemmusscope.readthedocs.io/en/latest/installation_instructions/), 3. [Running the STEMMUS_SCOPE model](https://pystemmusscope.readthedocs.io/en/latest/notebooks/run_model_in_notebook/)

**Comment by MostafaGomaa93** [comment] 2023-11-01 09:10
Is there a small test (with all required inputs) available that I can use to run the model and figure out more where are the problems?

**Comment by MostafaGomaa93** [comment] 2023-11-01 09:15
@SarahAlidoost 
can I get a copy of the test model that is used in the pystemmusscope [notebook][(url](https://pystemmusscope.readthedocs.io/en/latest/notebooks/run_model_in_notebook/))

**Comment by SarahAlidoost** [comment] 2023-11-01 10:50
> @SarahAlidoost can I get a copy of the test model files that are used in the pystemmusscope [notebook](https://pystemmusscope.readthedocs.io/en/latest/notebooks/run_model_in_notebook/)?

yes, I just ran the model on **CRIB** using the **Octave** option explained in the notebook and copied the input and output files to `shared/EcoExtreML/pystemmusscope_notebook_results`

**Comment by MostafaGomaa93** [comment] 2023-11-01 10:57
@SarahAlidoost 
Thanks so much. I will try it

**Comment by MostafaGomaa93** [comment] 2023-11-02 15:32
@SarahAlidoost 

I have tried the test model in Crib (with the assistance of Bas, our ITC-WRS developer). Here are some conclusions we had

1. The model doesn't run through the Octave option. It shows the below error of missing package. We have tried to install this statistics package, but doesn't work, because it asked for Octave 7.2. and the Octave version of Crib is 7.1. and we don't have the right to upgrade Octave in Crib.
![Screenshot 2023-11-02 151916](https://github.com/EcoExtreML/STEMMUS_SCOPE/assets/54531356/8b98500b-b199-413d-94ff-3e84da68083c)

2. The model runs through the Matlab option but only through the terminal inside the Crib Remote Desktop, so in Crib -> we open the Remote Desktop -> open a terminal -> run the model -> it will ask to activate the Matlab licence (screenshot below) -> runs successfully. 
![Screenshot 2023-11-02 141717](https://github.com/EcoExtreML/STEMMUS_SCOPE/assets/54531356/ce44e2c7-c52d-4ba5-9817-b3dd793a6261)

 
4. However, when we tried to run the model again in the normal terminal of Crib (which is outside the Crib Remote Desktop), it didn't run. Bas expects that the normal terminal somehow can not connect to Matlab (we didn't receive the request to access Matlab as was the case when we ran through the terminal inside the Crib Remote Desktop). This was strange to us and we don't know why.

**Comment by SarahAlidoost** [comment] 2023-11-02 16:22
> @SarahAlidoost
> 
> I have tried the test model in Crib (with the assistance of Bas, our ITC-WRS developer). Here are some conclusions we had
> 
> 1. The model doesn't run through the Octave option. It shows the below error of missing package. We have tried to install this statistics package, but doesn't work, because it asked for Octave 7.2. and the Octave version of Crib is 7.1. and we don't have the right to upgrade Octave in Crib.
>    ![Screenshot 2023-11-02 151916](https://user-images.githubusercontent.com/54531356/280043775-8b98500b-b199-413d-94ff-3e84da68083c.png)

There is an [octave instruction](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/Octave_instructions.md#using-stemmus-scope-with-gnu-octave) in the STEMUUS_SCOPE repository where it explained which versions of `io` and `statistics` packages to install i.e. `io-2.6.4.tar.gz` and `statistics-1.4.3.tar.gz`

> 3. However, when we tried to run the model again in the normal terminal of Crib (which is outside the Crib Remote Desktop), it didn't run. Bas expects that the normal terminal somehow can not connect to Matlab (we didn't receive the request to access Matlab as was the case when we ran through the terminal inside the Crib Remote Desktop). This was strange to us and we don't know why.

I noticed the same issue about CRIB and MATLAB. The notebook with octave option is a solution to this problem. Alternatively, you can run the model on SURF Snelius or your own machine using exe file that does not need matlab license.

**Comment by SarahAlidoost** [comment] 2023-11-07 14:49
> My main intention is to indeed run the model on my own machine (e.g. ITC Linux 668 server). 

I don't have access to ITC Linux 668 server. Can you tell me the version of MATLAB on the server?

> I have tried to run the same test model (using the Matlab option) on the server that already runs on Crib, 

Were you able to run the model on CRIB using matlab?

> but I have received the below error.

There are several reasons why there is such error, see some issues

- [How to solve this error "Operands to the || and && operators must be convertible to logical scalar values." ?](https://nl.mathworks.com/matlabcentral/answers/77558-how-to-solve-this-error-operands-to-the-and-operators-must-be-convertible-to-logical-scalar-v)
- [Operands to the || and && operators must be convertible to logical scalar values.](https://nl.mathworks.com/matlabcentral/answers/143576-operands-to-the-and-operators-must-be-convertible-to-logical-scalar-values)

> Any suggestion?

1. inspect the values of `SAVEhh`
2. As suggested by MATLAB, use `any` function for checking the values of `SAVEhh` for example `if any(isnan(SAVEhh)) || any(~isreal(SAVEhh))`. If you are fixing this line of the code, please make a pull request to contribute your fixes into the model.

**Comment by MostafaGomaa93** [comment] 2023-11-08 10:46
@SarahAlidoost 
Okay, I think I found where is the problem. Indeed the any() function was needed to let the model run. So, I tried this change as you mentioned and the model runs successfully on the Linux668 (with MATLAB 2022b v9.13.0 and with input/output via pystemmusscope). 

I also realized why the model was running on Crib and not on the server (before the change above). The source code on Crib is still the old one and not the refactored one. I copied the refactored source code in Crib and it didn't run, which proves that the issue was not about the machine type, the MATLAB version, or the inputs, but the issue was the slight change needed in line 24 in the **solveTridiagonalMatrixEquation.m** file. I will suggest this change in a separate pull request

So, now the model runs on the Linux machine using the MATLAB option (great success hhhh). Still running through the executable is not working. I have tried to create a new exe file from the source code (with the any() function) change using the command I found in the **build_stemmus_scope_exe.sh file** (**mcc -m ./src/STEMMUS_SCOPE_exe.m -a ./src -d ./run_model_on_snellius/exe -o STEMMUS_SCOPE -R nodisplay -R singleCompThread**), but still the model doesn't run with this new exe file. maybe I am missing something!

**Comment by SarahAlidoost** [comment] 2023-11-08 13:20
> @SarahAlidoost Okay, I think I found where is the problem. Indeed the any() function was needed to let the model run. So, I tried this change as you mentioned (**if any(isnan(SAVEhh)) || any(~isreal(SAVEhh))**) and the model runs successfully on the Linux668 (with MATLAB 2022b v9.13.0 and with input/output via pystemmusscope).

The MATLAB version on CRIB and snellius is `2021a`.

> I also realized why the model was running on Crib and not on the server (before the change above). The source code on Crib is still the old one and not the refactored one. I copied the refactored source code in Crib 

I suggest not using the source code on `shared` directory on CRIB as it seems it has not been maintained. But either download the latest version from the release page or clone the STEMMUS_SCOPE github repository under your won user directory on CRIB.

>and it didn't run, which proves that the issue was not about the machine type, the MATLAB version, or the inputs, but the issue was the slight change (any() function) needed in line 24 in the **solveTridiagonalMatrixEquation.m** file.

Please note that the latest version of the model is tested using matlab and exe on linux machines e.g. snelius and using octave on crib. So, I think since the matlab version on the ITC Linux server is different, this might be the cause of the issue.

> I will suggest this change in a separate pull request

Thank you, I will review the pull request.

> So, now the model runs on the Linux machine using the MATLAB option (great success hhhh). Still running through the executable is not working. I have tried to create a new exe file from the source code (with the any() function) change using the command I found in the **build_stemmus_scope_exe.sh file** (**mcc -m ./src/STEMMUS_SCOPE_exe.m -a ./src -d ./run_model_on_snellius/exe -o STEMMUS_SCOPE -R nodisplay -R singleCompThread**), 

If others also use ITC linux server, I suggest using a different output directory for example `run_model_on_itc_linux668` and sharing it with a separate pull request. This way others can also use the same exe file. 

> but still the model doesn't run with this new exe file. maybe I am missing something!

What is the error?  one guess is  `LD_LIBRARY_PATH`. As explained in the [notebook](https://pystemmusscope.readthedocs.io/en/latest/notebooks/run_model_in_notebook/), when using the exe file on your own machine, make sure `LD_LIBRARY_PATH` is set correctly. See cell number 18 in the notebook. This shows how to set `LD_LIBRARY_PATH` using python. You can do the same things using bash. Perhaps the server administrator can help with this.

**Comment by SarahAlidoost** [comment] 2023-11-08 14:08
@MostafaGomaa93 I generated a new exe file based on your fixes in #203 and merged your pull request. Could you please run the model on ITC linux serve with a matlab runtime that matches matlab version `2021a`? Please set the `LD_LIBRARY_PATH` before running the model.

**Comment by MostafaGomaa93** [comment] 2023-11-08 14:17
@SarahAlidoost 
Yes, I just tested the new exe in the Linux server and finally, it works. So now it works with both options via Matlab and via the exe. Thanks so much. It took a while to get it but I am very happy that I can go forward (thanks again for your efforts). May I get your email? I have a question but not related to this issue.

**Comment by SarahAlidoost** [comment] 2023-11-08 15:10
> @SarahAlidoost Yes, I just tested the new exe in the Linux server and finally, it works. So now it works with both options via Matlab and via the exe. Thanks so much. It took a while to get it but I am very happy that I can go forward (thanks again for your efforts).

Thanks for checking it :+1: I close this issue and open another issue about the documentation. 

> May I get your email? I have a question but not related to this issue.

My email address is on my [profile page](https://www.esciencecenter.nl/team/dr-fakhereh-sarah-alidoost/). 
Please note if your question is about the project please cc @yijianzeng. You can also submit it on the [Discussion page](https://github.com/orgs/EcoExtreML/discussions). This way people with the same question can find the answer.

**Closed** 2023-11-08 15:13 UTC
Labels: bug, documentation
